name: detect-base-branch-updated
on:
  push:
    branches:
      - 'develop'

jobs:
  Merge-develop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
